# Generated by Django 4.1 on 2022-08-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KTFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=360)),
                ('file_uri', models.FilePathField()),
                ('lines_count', models.IntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
